-- 天猫自营_生意参谋_商品排行日数据
drop table if exists sales_tm_sycm_goods_ranking_dly;
CREATE TABLE sales_tm_sycm_goods_ranking_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺名称',
    stat_date VARCHAR(10) COMMENT '统计日期',
    product_id VARCHAR(20) COMMENT '商品ID',
    product_name VARCHAR(512) COMMENT '商品名称',
    main_product_id VARCHAR(20) COMMENT '主商品ID',
    product_type VARCHAR(50) COMMENT '商品类型',
    product_code VARCHAR(20) COMMENT '货号',
    status VARCHAR(20) COMMENT '商品状态',
    tags VARCHAR(100) COMMENT '商品标签',
    visitors VARCHAR(10) COMMENT '商品访客数',
    page_views VARCHAR(10) COMMENT '商品浏览量',
    avg_duration VARCHAR(10) COMMENT '平均停留时长',
    bounce_rate VARCHAR(10) COMMENT '商品详情页跳出率',
    favor_users VARCHAR(10) COMMENT '商品收藏人数',
    cart_quantity VARCHAR(10) COMMENT '商品加购件数',
    cart_users VARCHAR(10) COMMENT '商品加购人数',
    order_users VARCHAR(10) COMMENT '下单买家数',
    order_quantity VARCHAR(10) COMMENT '下单件数',
    order_amount VARCHAR(20) COMMENT '下单金额',
    order_conv_rate VARCHAR(10) COMMENT '下单转化率',
    pay_users VARCHAR(10) COMMENT '支付买家数',
    pay_quantity VARCHAR(10) COMMENT '支付件数',
    total_pay_quantity VARCHAR(10) COMMENT '总支付商品件数',
    pay_amount VARCHAR(20) COMMENT '支付金额',
    total_pay_amount VARCHAR(20) COMMENT '总支付金额',
    pay_conv_rate VARCHAR(10) COMMENT '商品支付转化率',
    new_pay_users VARCHAR(10) COMMENT '支付新买家数',
    old_pay_users VARCHAR(10) COMMENT '支付老买家数',
    old_pay_amount VARCHAR(20) COMMENT '老买家支付金额',
    jhs_pay_amount VARCHAR(20) COMMENT '聚划算支付金额',
    avg_visitor_value VARCHAR(10) COMMENT '访客平均价值',
    refund_amount VARCHAR(20) COMMENT '成功退款金额',
    comp_score VARCHAR(10) COMMENT '竞争力评分',
    annual_pay_amount VARCHAR(20) COMMENT '年累计支付金额',
    monthly_pay_amount VARCHAR(20) COMMENT '月累计支付金额',
    monthly_pay_quantity VARCHAR(10) COMMENT '月累计支付件数',
    search_conv_rate VARCHAR(10) COMMENT '搜索引导支付转化率',
    search_visitors VARCHAR(10) COMMENT '搜索引导访客数',
    search_pay_users VARCHAR(10) COMMENT '搜索引导支付买家数',
    detail_conv_rate VARCHAR(10) COMMENT '结构化详情引导转化率',
    detail_pay_ratio VARCHAR(10) COMMENT '结构化详情引导成交占比',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫自营_生意参谋_商品排行日数据';

-- 天猫自营_万相台_站内推广费日数据
drop table if exists sales_tm_wxt_promotion_fee_dly;
CREATE TABLE sales_tm_wxt_promotion_fee_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺名称',
    stat_date VARCHAR(10) COMMENT '日期',
    entity_id VARCHAR(64) COMMENT '主体ID',
    entity_type VARCHAR(32) COMMENT '主体类型',
    entity_name VARCHAR(255) COMMENT '主体名称',
    impressions VARCHAR(20) COMMENT '展现量',
    clicks VARCHAR(20) COMMENT '点击量',
    cost VARCHAR(20) COMMENT '花费',
    click_rate VARCHAR(10) COMMENT '点击率',
    avg_click_cost VARCHAR(20) COMMENT '平均点击花费',
    cpm VARCHAR(20) COMMENT '千次展现花费',
    total_pre_sale_amount VARCHAR(20) COMMENT '总预售成交金额',
    total_pre_sale_cnt VARCHAR(10) COMMENT '总预售成交笔数',
    direct_pre_sale_amount VARCHAR(20) COMMENT '直接预售成交金额',
    direct_pre_sale_cnt VARCHAR(10) COMMENT '直接预售成交笔数',
    indirect_pre_sale_amount VARCHAR(20) COMMENT '间接预售成交金额',
    indirect_pre_sale_cnt VARCHAR(10) COMMENT '间接预售成交笔数',
    direct_gmv VARCHAR(20) COMMENT '直接成交金额',
    indirect_gmv VARCHAR(20) COMMENT '间接成交金额',
    total_gmv VARCHAR(20) COMMENT '总成交金额',
    total_order_cnt VARCHAR(10) COMMENT '总成交笔数',
    direct_order_cnt VARCHAR(10) COMMENT '直接成交笔数',
    indirect_order_cnt VARCHAR(10) COMMENT '间接成交笔数',
    conversion_rate VARCHAR(10) COMMENT '点击转化率',
    roi VARCHAR(20) COMMENT '投入产出比',
    total_cost VARCHAR(20) COMMENT '总成交成本',
    total_cart VARCHAR(20) COMMENT '总购物车数',
    direct_cart VARCHAR(20) COMMENT '直接购物车数',
    indirect_cart VARCHAR(20) COMMENT '间接购物车数',
    cart_rate VARCHAR(10) COMMENT '加购率',
    fav_items VARCHAR(20) COMMENT '收藏宝贝数',
    fav_shops VARCHAR(20) COMMENT '收藏店铺数',
    shop_fav_cost VARCHAR(20) COMMENT '店铺收藏成本',
    total_fav_cart VARCHAR(20) COMMENT '总收藏加购数',
    total_fav_cart_cost VARCHAR(20) COMMENT '总收藏加购成本',
    item_fav_cart VARCHAR(20) COMMENT '宝贝收藏加购数',
    item_fav_cart_cost VARCHAR(20) COMMENT '宝贝收藏加购成本',
    total_fav VARCHAR(20) COMMENT '总收藏数',
    item_fav_cost VARCHAR(20) COMMENT '宝贝收藏成本',
    item_fav_rate VARCHAR(10) COMMENT '宝贝收藏率',
    cart_cost VARCHAR(20) COMMENT '加购成本',
    order_cnt VARCHAR(20) COMMENT '拍下订单笔数',
    order_amount VARCHAR(20) COMMENT '拍下订单金额',
    direct_fav_items VARCHAR(20) COMMENT '直接收藏宝贝数',
    indirect_fav_items VARCHAR(20) COMMENT '间接收藏宝贝数',
    coupon_claims VARCHAR(20) COMMENT '优惠券领取量',
    recharge_cnt VARCHAR(20) COMMENT '购物金充值笔数',
    recharge_amount VARCHAR(20) COMMENT '购物金充值金额',
    ww_consult VARCHAR(20) COMMENT '旺旺咨询量',
    guide_uv VARCHAR(20) COMMENT '引导访问量',
    guide_visitors VARCHAR(20) COMMENT '引导访问人数',
    guide_potential_uv VARCHAR(20) COMMENT '引导访问潜客数',
    guide_potential_ratio VARCHAR(10) COMMENT '引导访问潜客占比',
    member_rate VARCHAR(10) COMMENT '入会率',
    new_members VARCHAR(20) COMMENT '入会量',
    guide_uv_rate VARCHAR(10) COMMENT '引导访问率',
    deep_uv VARCHAR(20) COMMENT '深度访问量',
    avg_page_view VARCHAR(10) COMMENT '平均访问页面数',
    new_customers VARCHAR(20) COMMENT '成交新客数',
    new_customer_ratio VARCHAR(10) COMMENT '成交新客占比',
    first_purchase_members VARCHAR(20) COMMENT '会员首购人数',
    member_gmv VARCHAR(20) COMMENT '会员成交金额',
    member_orders VARCHAR(20) COMMENT '会员成交笔数',
    total_buyers VARCHAR(20) COMMENT '成交人数',
    avg_order_per_buyer VARCHAR(10) COMMENT '人均成交笔数',
    avg_gmv_per_buyer VARCHAR(20) COMMENT '人均成交金额',
    organic_gmv VARCHAR(20) COMMENT '自然流量转化金额',
    organic_impressions VARCHAR(20) COMMENT '自然流量曝光量',
    platform_gmv VARCHAR(20) COMMENT '平台助推总成交',
    platform_direct_gmv VARCHAR(20) COMMENT '平台助推直接成交',
    platform_clicks VARCHAR(20) COMMENT '平台助推点击',
    coupon_deduction VARCHAR(20) COMMENT '宝贝优惠券抵扣金额',
    coupon_gmv VARCHAR(20) COMMENT '宝贝优惠券撬动总成交',
    coupon_direct_gmv VARCHAR(20) COMMENT '宝贝优惠券撬动直接成交',
    coupon_clicks VARCHAR(20) COMMENT '宝贝优惠券撬动点击',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫自营_万相台_站内推广费日数据';

-- 天猫自营_喵速达_订单明细日数据
drop table if exists sales_tm_msd_order_detail_dly;
CREATE TABLE sales_tm_msd_order_detail_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    shop_name VARCHAR(50) COMMENT '店铺名称',
    warehouse_name VARCHAR(50) COMMENT '仓库名称',
    order_time VARCHAR(64) COMMENT '下单时间',
    pay_time VARCHAR(64) COMMENT '支付时间',
    ship_time VARCHAR(64) COMMENT '发货时间',
    order_status VARCHAR(64) COMMENT '订单状态',
    logistics_no VARCHAR(50) COMMENT '物流订单号',
    transaction_no VARCHAR(50) COMMENT '交易订单号',
    warehouse_order_no VARCHAR(30) COMMENT '仓库订单号',
    shipping_company VARCHAR(30) COMMENT '配送公司',
    tracking_no VARCHAR(50) COMMENT '配送运单号',
    buyer_nickname VARCHAR(50) COMMENT '买家昵称',
    receiver_name VARCHAR(50) COMMENT '收件人',
    province VARCHAR(30) COMMENT '省',
    city VARCHAR(30) COMMENT '市',
    district VARCHAR(30) COMMENT '区',
    street VARCHAR(50) COMMENT '街道',
    detail_address VARCHAR(255) COMMENT '详细地址',
    mobile VARCHAR(64) COMMENT '手机',
    order_amount VARCHAR(64) COMMENT '订单金额',
    freight VARCHAR(64) COMMENT '运费',
    goods_quantity VARCHAR(10) COMMENT '商品数量',
    goods_id VARCHAR(64) COMMENT '货品id',
    sku_code VARCHAR(30) COMMENT '货品编码',
    product_id VARCHAR(64) COMMENT '商品id',
    merchant_sku VARCHAR(30) COMMENT '商家编码',
    goods_name VARCHAR(255) COMMENT '商品名称',
    tax_amount VARCHAR(64) COMMENT '税费',
    tax_included_amount VARCHAR(64) COMMENT '商品包税金额',
    external_order_no VARCHAR(50) COMMENT '外部订单号',
    barcode VARCHAR(1024) COMMENT '条码',
    scp_no VARCHAR(64) COMMENT 'SCP单号',
    specs VARCHAR(255) COMMENT '规格',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫自营_喵速达_订单明细日数据';

-- 天猫国际_直营商家工作台_订单明细日数据
drop table if exists sales_tmgj_wp_order_detail_dly;
CREATE TABLE sales_tmgj_wp_order_detail_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    shop_name VARCHAR(50) COMMENT '店铺名称',
    warehouse_name VARCHAR(50) COMMENT '仓库名称',
    external_gift VARCHAR(10) COMMENT '仓外赠品',
    warehouse_code VARCHAR(20) COMMENT '仓库编码',
    warehouse_type VARCHAR(20) COMMENT '仓类型',
    order_time VARCHAR(20) COMMENT '下单时间',
    pay_time VARCHAR(20) COMMENT '支付时间',
    ship_time VARCHAR(20) COMMENT '发货时间',
    delivery_period VARCHAR(20) COMMENT '发货时效',
    order_status VARCHAR(20) COMMENT '订单状态',
    logistics_no VARCHAR(50) COMMENT '物流订单号',
    transaction_no VARCHAR(50) COMMENT '交易订单号',
    sub_transaction_no VARCHAR(50) COMMENT '子交易单号',
    warehouse_order_no VARCHAR(30) COMMENT '仓库订单号',
    shipping_company VARCHAR(30) COMMENT '配送公司',
    tracking_no VARCHAR(50) COMMENT '配送运单号',
    buyer_nickname VARCHAR(50) COMMENT '买家昵称',
    receiver_name VARCHAR(50) COMMENT '收件人',
    province VARCHAR(30) COMMENT '省',
    city VARCHAR(30) COMMENT '市',
    district VARCHAR(30) COMMENT '区',
    street VARCHAR(50) COMMENT '街道',
    mobile VARCHAR(20) COMMENT '手机',
    order_amount VARCHAR(20) COMMENT '订单金额',
    freight VARCHAR(20) COMMENT '运费',
    goods_quantity VARCHAR(10) COMMENT '商品数量',
    goods_id VARCHAR(20) COMMENT '货品id',
    sku_code VARCHAR(30) COMMENT '货品编码',
    goods_name VARCHAR(255) COMMENT '货品名称',
    product_id VARCHAR(20) COMMENT '商品id',
    product_code VARCHAR(30) COMMENT '商品编码',
    product_name VARCHAR(255) COMMENT '商品名称',
    tax_amount VARCHAR(20) COMMENT '税费',
    tax_included_amount VARCHAR(20) COMMENT '商品包税金额',
    external_order_no VARCHAR(50) COMMENT '外部订单号',
    barcode VARCHAR(255) COMMENT '条码',
    scp_no VARCHAR(30) COMMENT 'SCP单号',
    specs VARCHAR(255) COMMENT '规格',
    real_name_auth VARCHAR(5) COMMENT '是否实名认证',
    spring_festival VARCHAR(5) COMMENT '春节不打烊(0打烊,1不打烊)',
    door_delivery VARCHAR(10) COMMENT '送货上门',
    delay_type VARCHAR(20) COMMENT '延迟订单类型',
    report_status VARCHAR(20) COMMENT '报备状态',
    report_type VARCHAR(20) COMMENT '报备类型',
    report_reason VARCHAR(100) COMMENT '报备原因',
    report_remark VARCHAR(255) COMMENT '报备说明',
    scheduled_ship_time VARCHAR(20) COMMENT '应发货时间',
    supplier_id VARCHAR(20) COMMENT '二级供应商ID',
    supplier_name VARCHAR(50) COMMENT '二级供应商名称',
    service_order VARCHAR(30) COMMENT '服务工单',
    qc_first_shipment VARCHAR(30) COMMENT '质检一段运单',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫国际_直营商家工作台_订单明细日数据';

-- 天猫国际_直营商家工作台_退款明细日数据
drop table if exists sales_tmgj_wp_refund_detail_dly;
CREATE TABLE sales_tmgj_wp_refund_detail_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    order_no VARCHAR(50) COMMENT '订单号',
    main_order_no VARCHAR(50) COMMENT '主订单号',
    refund_no VARCHAR(50) COMMENT '退款单号',
    order_pay_time VARCHAR(20) COMMENT '订单付款时间',
    product_name VARCHAR(255) COMMENT '商品名称',
    product_id VARCHAR(20) COMMENT '商品ID',
    shop_name VARCHAR(50) COMMENT '店铺名称',
    buyer_payment VARCHAR(20) COMMENT '买家实付金额',
    buyer_refund_amount VARCHAR(20) COMMENT '买家退款金额',
    refund_apply_time VARCHAR(20) COMMENT '退款申请时间',
    refund_complete_time VARCHAR(20) COMMENT '退款完结时间',
    timeout_time VARCHAR(20) COMMENT '超时时间',
    return_required VARCHAR(5) COMMENT '是否需要退货',
    refund_status VARCHAR(20) COMMENT '退款状态',
    goods_status VARCHAR(20) COMMENT '货物状态',
    service_phase VARCHAR(10) COMMENT '售中或售后',
    refund_reason VARCHAR(100) COMMENT '退款原因',
    order_source VARCHAR(30) COMMENT '订单来源',
    platform_order_no VARCHAR(50) COMMENT '平台单号',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫国际_直营商家工作台_退款明细日数据';

-- 天猫超市_天机_商品销售排行日数据
drop table if exists sales_tmcs_tj_goods_ranking_dly;
CREATE TABLE sales_tmcs_tj_goods_ranking_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    product_img     VARCHAR(255) COMMENT '商品图片',
    product_name    VARCHAR(200) COMMENT '商品名称',
    product_id      VARCHAR(20)  COMMENT '商品ID',
    stat_date       VARCHAR(10)  COMMENT '统计日期',
    category_l4     VARCHAR(50)  COMMENT '四级类目',
    region          VARCHAR(50)  COMMENT '区域',
    brand           VARCHAR(50)  COMMENT '品牌',
    category_id     VARCHAR(10)  COMMENT '类目ID',
    region_id       VARCHAR(10)  COMMENT '区域ID',
    brand_id        VARCHAR(10)  COMMENT '品牌ID',
    supplier_name   VARCHAR(100) COMMENT '供应商名称',
    original_price  VARCHAR(20)  COMMENT '一口价',
    price_ratio     VARCHAR(10)  COMMENT '一口价环比',
    order_count     VARCHAR(10)  COMMENT '支付子订单数',
    order_ratio     VARCHAR(10)  COMMENT '支付子订单数环比',
    quantity        VARCHAR(10)  COMMENT '支付商品件数',
    quantity_ratio  VARCHAR(10)  COMMENT '支付商品件数环比',
    net_order_count VARCHAR(10)  COMMENT '支付子订单数(剔退款)',
    net_order_ratio VARCHAR(10)  COMMENT '支付子订单数(剔退款)环比',
    refund_order    VARCHAR(10)  COMMENT '发起退款子订单数',
    refund_order_rt VARCHAR(10)  COMMENT '发起退款子订单数环比',
    refund_quantity VARCHAR(10)  COMMENT '发起退款商品件数',
    refund_qty_rt  VARCHAR(10)  COMMENT '发起退款商品件数环比',
    succ_refund_ord VARCHAR(10)  COMMENT '退款成功子订单数',
    succ_refund_rt  VARCHAR(10)  COMMENT '退款成功子订单数环比',
    succ_refund_qty VARCHAR(10)  COMMENT '退款成功商品件数',
    succ_refund_q_rt VARCHAR(10) COMMENT '退款成功商品件数环比',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫超市_天机_商品销售排行日数据';


-- 天猫超市_智多星_站内推广费日数据
drop table if exists sales_tmcs_zdx_promotion_fee_dly;
CREATE TABLE sales_tmcs_zdx_promotion_fee_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date        VARCHAR(10)  COMMENT '日期',
    conv_cycle       VARCHAR(20)  COMMENT '转化周期',
    ad_scene         VARCHAR(50)  COMMENT '投放场景',
    cost             VARCHAR(20)  COMMENT '消耗(元)',
    impressions      VARCHAR(20)  COMMENT '曝光量',
    clicks           VARCHAR(20)  COMMENT '点击量',
    click_rate       VARCHAR(10)  COMMENT '点击率',
    click_cost       VARCHAR(10)  COMMENT '点击成本',
    cart_add         VARCHAR(20)  COMMENT '加购数',
    favorites        VARCHAR(20)  COMMENT '收藏数',
    direct_orders    VARCHAR(20)  COMMENT '直接成交笔数',
    total_orders     VARCHAR(20)  COMMENT '总成交笔数',
    direct_gmv       VARCHAR(20)  COMMENT '直接成交金额',
    total_gmv        VARCHAR(20)  COMMENT '总成交金额',
    conversion_rate  VARCHAR(10)  COMMENT '成交转化率',
    roi              VARCHAR(10)  COMMENT 'ROI',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '天猫超市_智多星_站内推广费日数据';


-- 京东自营_京麦_商品业绩日数据
drop table if exists sales_jd_jm_goods_performance_dly;
CREATE TABLE sales_jd_jm_goods_performance_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    record_time VARCHAR(20) COMMENT '日期' ,
    product_id VARCHAR(512) COMMENT '商品ID' ,
    product_name VARCHAR(512) COMMENT '商品名称' ,
    financial_sales VARCHAR(20) COMMENT '财务销量' ,
    revenue VARCHAR(20) COMMENT '收入' ,
    cost VARCHAR(20) COMMENT '成本' ,
    gross_profit VARCHAR(20) COMMENT '毛利' ,
    coupon_deduction VARCHAR(20) COMMENT '优惠券抵减数' ,
    points_deduction VARCHAR(20) COMMENT '积分抵减数' ,
    promotion_amount VARCHAR(20) COMMENT '满返满减额' ,
    inventory_turnover_days VARCHAR(20) COMMENT '库存周转天数',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '京东自营_京麦_商品业绩日数据';


-- 京东自营_精准通_站内推广费日数据
drop table if exists sales_jd_jzt_promotion_fee_dly;
CREATE TABLE sales_jd_jzt_promotion_fee_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    record_date VARCHAR(64) COMMENT '日期' ,
    product_line VARCHAR(255) COMMENT '产品线' ,
    plan_id VARCHAR(255) COMMENT '计划ID' ,
    promo_plan VARCHAR(255) COMMENT '推广计划' ,
    unit_id VARCHAR(255) COMMENT '单元ID' ,
    promo_unit VARCHAR(50) COMMENT '推广单元' ,
    category_id VARCHAR(255) COMMENT '品类id' ,
    promo_category VARCHAR(255) COMMENT '推广品类' ,
    creative_id VARCHAR(255) COMMENT '创意ID' ,
    promo_creative VARCHAR(255) COMMENT '推广创意' ,
    smart_sku_id VARCHAR(255) COMMENT '智能投放推广SKU ID' ,
    smart_sku_name VARCHAR(255) COMMENT '智能投放推广SKU名称' ,
    plan_type VARCHAR(20) COMMENT '计划类型' ,
    track_sku_id VARCHAR(15) COMMENT '跟单SKU ID' ,
    track_sku_name VARCHAR(200) COMMENT '跟单SKU名称' ,
    impressions VARCHAR(20) COMMENT '展现数' ,
    clicks VARCHAR(20) COMMENT '点击数' ,
    click_rate VARCHAR(10) COMMENT '点击率(%)' ,
    cost VARCHAR(20) COMMENT '花费' ,
    cpm VARCHAR(10) COMMENT '千次展现成本' ,
    cpc VARCHAR(10) COMMENT '平均点击成本' ,
    direct_orders VARCHAR(20) COMMENT '直接订单行' ,
    direct_amount VARCHAR(20) COMMENT '直接订单金额' ,
    indirect_orders VARCHAR(20) COMMENT '间接订单行' ,
    indirect_amount VARCHAR(20) COMMENT '间接订单金额' ,
    total_orders VARCHAR(20) COMMENT '总订单行' ,
    total_amount VARCHAR(20) COMMENT '总订单金额' ,
    direct_cart VARCHAR(20) COMMENT '直接加购数' ,
    indirect_cart VARCHAR(20) COMMENT '间接加购数' ,
    total_cart VARCHAR(20) COMMENT '总加购数' ,
    conversion_rate VARCHAR(10) COMMENT '转化率(%)' ,
    avg_order_cost VARCHAR(20) COMMENT '平均订单成本' ,
    roi VARCHAR(10) COMMENT '投产比' ,
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '京东自营_精准通_站内推广费日数据';

-- 京东pop_商智_商品明细日数据
drop table if exists sales_jdpop_sz_goods_details_dly;
CREATE TABLE sales_jd_sz_goods_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    product_id VARCHAR(20) COMMENT '商品ID',
    product_name VARCHAR(100) COMMENT '商品名称',
    product_code VARCHAR(20) COMMENT '货号',
    visitors VARCHAR(10) COMMENT '访客数',
    page_views VARCHAR(10) COMMENT '浏览量',
    followers VARCHAR(10) COMMENT '商品关注数',
    cart_items VARCHAR(10) COMMENT '加购商品件数',
    cart_users VARCHAR(10) COMMENT '加购人数',
    buyers VARCHAR(10) COMMENT '成交客户数',
    orders VARCHAR(10) COMMENT '成交单量',
    sold_items VARCHAR(10) COMMENT '成交商品件数',
    transaction_amount VARCHAR(20) COMMENT '成交金额',
    conversion_rate VARCHAR(10) COMMENT '成交转化率',
    uv_value VARCHAR(10) COMMENT 'UV价值',
    last_listing_time VARCHAR(20) COMMENT '最近上架时间',
    detail_bounce_rate VARCHAR(10) COMMENT '详情页跳出率',
    search_exposure VARCHAR(10) COMMENT '搜索曝光量',
    search_clicks VARCHAR(10) COMMENT '搜索点击次数',
    search_ctr VARCHAR(10) COMMENT '搜索点击率',
    pred_7d_sales VARCHAR(10) COMMENT '系统预测未来7天销量',
    order_users VARCHAR(10) COMMENT '下单客户数',
    order_items VARCHAR(10) COMMENT '下单商品件数',
    order_amount VARCHAR(20) COMMENT '下单金额',
    order_conversion VARCHAR(10) COMMENT '下单成交转化率',
    order_rate VARCHAR(10) COMMENT '下单转化率',
    pv_stock_rate VARCHAR(10) COMMENT 'PV现货率',
    avg_order_value VARCHAR(10) COMMENT '客单价',
    avg_item_price VARCHAR(10) COMMENT '件单价',
    cancel_refund_amount VARCHAR(20) COMMENT '取消及售后退款金额',
    cancel_refund_items VARCHAR(10) COMMENT '取消及售后退款件数',
    cancel_refund_orders VARCHAR(10) COMMENT '取消及售后退款单量',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '京东pop_商智_商品明细日数据';


-- 京东pop_精准通_单品推广明细日数据
drop table if exists sales_jdpop_jzt_promotion_details_dly;
CREATE TABLE sales_jd_jzt_promotion_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    plan_name VARCHAR(100) COMMENT '商品计划名称',
    campaign_id VARCHAR(20) COMMENT 'ID',
    campaign_type VARCHAR(20) COMMENT '投放类型',
    cost VARCHAR(20) COMMENT '花费',
    roi VARCHAR(10) COMMENT '全站投产比',
    total_revenue VARCHAR(20) COMMENT '全站交易额',
    total_orders VARCHAR(10) COMMENT '全站订单行',
    order_cost VARCHAR(20) COMMENT '全站订单成本',
    core_impressions VARCHAR(10) COMMENT '核心位置展现量',
    core_clicks VARCHAR(10) COMMENT '核心位置点击量',
    new_customers_180d VARCHAR(10) COMMENT '180天未购新客数',
    coupon_impressions VARCHAR(10) COMMENT '带券展现',
    coupon_clicks VARCHAR(10) COMMENT '带券点击',
    smart_coupon_amount VARCHAR(20) COMMENT '智能补贴券金额',
    smart_coupon_orders VARCHAR(10) COMMENT '智能补贴券助力订单行',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '京东pop_精准通_单品推广明细日数据';


-- 拼多多_商家后台_订单明细日数据
drop table if exists sales_pdd_ht_order_details_dly;
CREATE TABLE sales_pdd_ht_order_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    product_name VARCHAR(255) COMMENT '商品',
    order_id VARCHAR(64) COMMENT '订单号',
    order_status VARCHAR(20) COMMENT '订单状态',
    quantity VARCHAR(10) COMMENT '商品数量(件)',
    pay_time VARCHAR(20) COMMENT '支付时间',
    product_id VARCHAR(32) COMMENT '商品id',
    specs VARCHAR(255) COMMENT '商品规格',
    cat_l4 VARCHAR(32) COMMENT '商品四级类目',
    merchant_code_spec VARCHAR(64) COMMENT '商家编码-规格维度',
    merchant_code_product VARCHAR(64) COMMENT '商家编码-商品维度',
    merchant_notes VARCHAR(500) COMMENT '商家备注',
    buyer_notes VARCHAR(500) COMMENT '买家留言',
    after_sale_status VARCHAR(20) COMMENT '售后状态',
    order_time VARCHAR(20) COMMENT '订单成交时间',
    user_paid VARCHAR(20) COMMENT '用户实付金额(元)',
    merchant_received VARCHAR(20) COMMENT '商家实收金额(元)',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '拼多多_商家后台_订单明细日数据';

-- 拼多多_商家后台_售后明细日数据
drop table if exists sales_pdd_ht_after_sales_details_dly;
CREATE TABLE sales_pdd_ht_after_sales_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    after_sale_id VARCHAR(32) COMMENT '售后编号',
    order_id VARCHAR(32) COMMENT '订单编号',
    transaction_amount VARCHAR(20) COMMENT '交易金额',
    after_sale_status VARCHAR(20) COMMENT '售后状态',
    refund_type VARCHAR(20) COMMENT '退款类型',
    refund_amount VARCHAR(20) COMMENT '退款金额',
    order_status VARCHAR(20) COMMENT '订单状态',
    shipping_tracking_num VARCHAR(50) COMMENT '发货运单号',
    product_id VARCHAR(32) COMMENT '商品ID',
    buyer VARCHAR(50) COMMENT '买家',
    timeout_time VARCHAR(20) COMMENT '超时时间',
    apply_time VARCHAR(20) COMMENT '申请时间',
    refund_reason VARCHAR(100) COMMENT '退款原因',
    return_tracking_num VARCHAR(50) COMMENT '退货运单号',
    return_logistics_status VARCHAR(20) COMMENT '退货物流状态',
    status_update_time VARCHAR(20) COMMENT '退货物流状态对应时间',
    refund_approve_time VARCHAR(20) COMMENT '同意退款时间',
    refund_approver VARCHAR(50) COMMENT '同意退款人',
    return_approve_time VARCHAR(20) COMMENT '同意退货时间',
    return_approver VARCHAR(50) COMMENT '同意退货人',
    intercept_status VARCHAR(20) COMMENT '快递拦截状态',
    sku_info VARCHAR(100) COMMENT 'sku信息',
    order_tag VARCHAR(20) COMMENT '订单标记',
    remark VARCHAR(200) COMMENT '备注',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '拼多多_商家后台_售后明细日数据';

-- 拼多多_商家后台_商品推广明细日数据
drop table if exists sales_pdd_ht_goods_promotion_details_dly;
CREATE TABLE sales_pdd_ht_goods_promotion_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(10) COMMENT '日期',
    product_name VARCHAR(255) COMMENT '商品名称',
    product_id VARCHAR(255) COMMENT '商品ID',
    group_name VARCHAR(255) COMMENT '分组',
    campaign_name VARCHAR(255) COMMENT '推广名称',
    bid_type VARCHAR(255) COMMENT '出价方式',
    is_deleted VARCHAR(255) COMMENT '是否已删除',
    total_cost VARCHAR(255) COMMENT '总花费(元)',
    order_cost VARCHAR(255) COMMENT '成交花费(元)',
    gmv VARCHAR(255) COMMENT '交易额(元)',
    real_roi VARCHAR(255) COMMENT '实际投产比',
    net_real_roi VARCHAR(255) COMMENT '净实际投产比',
    net_gmv VARCHAR(255) COMMENT '净交易额(元)',
    net_order_count VARCHAR(255) COMMENT '净成交笔数',
    cost_per_net_order VARCHAR(255) COMMENT '每笔净成交花费(元)',
    net_gmv_ratio VARCHAR(255) COMMENT '净交易额占比',
    order_count VARCHAR(255) COMMENT '成交笔数',
    cost_per_order VARCHAR(255) COMMENT '每笔成交花费(元)',
    amount_per_order VARCHAR(255) COMMENT '每笔成交金额(元)',
    direct_gmv VARCHAR(255) COMMENT '直接交易额(元)',
    indirect_gmv VARCHAR(255) COMMENT '间接交易额(元)',
    direct_order_count VARCHAR(255) COMMENT '直接成交笔数',
    indirect_order_count VARCHAR(255) COMMENT '间接成交笔数',
    direct_amount_per_order VARCHAR(255) COMMENT '每笔直接成交金额(元)',
    indirect_amount_per_order VARCHAR(255) COMMENT '每笔间接成交金额(元)',
    site_promotion_ratio VARCHAR(255) COMMENT '全站推广费比',
    exposure_count VARCHAR(255) COMMENT '曝光量',
    click_count VARCHAR(255) COMMENT '点击量',
    inquiry_cost VARCHAR(255) COMMENT '询单花费(元)',
    inquiry_count VARCHAR(255) COMMENT '询单量',
    avg_inquiry_cost VARCHAR(255) COMMENT '平均询单成本(元)',
    favorite_cost VARCHAR(255) COMMENT '收藏花费(元)',
    favorite_count VARCHAR(255) COMMENT '收藏量',
    avg_favorite_cost VARCHAR(255) COMMENT '平均收藏成本(元)',
    follow_cost VARCHAR(255) COMMENT '关注花费(元)',
    follow_count VARCHAR(255) COMMENT '关注量',
    avg_follow_cost VARCHAR(255) COMMENT '平均关注成本(元)',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '拼多多_商家后台_商品推广明细日数据';

-- 拼多多_商家后台_推广效果明细日数据
drop table if exists sales_pdd_ht_promotion_effect_details_dly;
CREATE TABLE sales_pdd_ht_promotion_effect_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(64) COMMENT '日期',
    order_count VARCHAR(20) COMMENT '成交笔数',
    transaction_amount VARCHAR(20) COMMENT '成交金额(元)',
    estimated_commission VARCHAR(20) COMMENT '预估支付佣金(元)',
    estimated_service_fee VARCHAR(20) COMMENT '预估软件服务费（元）',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '拼多多_商家后台_推广效果明细日数据';


-- 抖音_后台_订单明细日数据
drop table if exists sales_dy_ht_order_details_dly;
CREATE TABLE sales_dy_ht_order_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    master_order_id VARCHAR(50) COMMENT '主订单编号',
    sub_order_id VARCHAR(50) COMMENT '子订单编号',
    product_name VARCHAR(255) COMMENT '选购商品',
    product_spec VARCHAR(100) COMMENT '商品规格',
    product_quantity VARCHAR(10) COMMENT '商品数量',
    product_id VARCHAR(50) COMMENT '商品ID',
    merchant_code VARCHAR(50) COMMENT '商家编码',
    unit_price VARCHAR(20) COMMENT '商品单价',
    order_payable_amount VARCHAR(20) COMMENT '订单应付金额',
    shipping_fee VARCHAR(20) COMMENT '运费',
    total_discount VARCHAR(20) COMMENT '优惠总金额',
    platform_discount VARCHAR(255) COMMENT '平台优惠',
    merchant_discount VARCHAR(255) COMMENT '商家优惠',
    talent_discount VARCHAR(255) COMMENT '达人优惠',
    merchant_price_adjust VARCHAR(20) COMMENT '商家改价',
    payment_discount VARCHAR(20) COMMENT '支付优惠',
    red_packet_deduction VARCHAR(20) COMMENT '红包抵扣',
    payment_method VARCHAR(50) COMMENT '支付方式',
    handling_fee VARCHAR(20) COMMENT '手续费',
    receiver_name VARCHAR(512) COMMENT '收件人',
    receiver_phone VARCHAR(512) COMMENT '收件人手机号',
    province VARCHAR(50) COMMENT '省',
    city VARCHAR(50) COMMENT '市',
    district VARCHAR(50) COMMENT '区',
    street VARCHAR(100) COMMENT '街道',
    detailed_address VARCHAR(512) COMMENT '详细地址',
    is_address_modified VARCHAR(1) COMMENT '是否修改过地址',
    buyer_comment VARCHAR(500) COMMENT '买家留言',
    order_submit_time VARCHAR(20) COMMENT '订单提交时间',
    flag_color VARCHAR(20) COMMENT '旗帜颜色',
    merchant_note VARCHAR(500) COMMENT '商家备注',
    order_complete_time VARCHAR(20) COMMENT '订单完成时间',
    payment_time VARCHAR(20) COMMENT '支付完成时间',
    app_channel VARCHAR(50) COMMENT 'APP渠道',
    traffic_source VARCHAR(50) COMMENT '流量来源',
    order_status VARCHAR(50) COMMENT '订单状态',
    promised_delivery_time VARCHAR(20) COMMENT '承诺发货时间',
    order_type VARCHAR(50) COMMENT '订单类型',
    luban_page_id VARCHAR(50) COMMENT '鲁班落地页ID',
    talent_id VARCHAR(50) COMMENT '达人ID',
    talent_nickname VARCHAR(100) COMMENT '达人昵称',
    shop_id VARCHAR(50) COMMENT '所属门店ID',
    after_sale_status VARCHAR(50) COMMENT '售后状态',
    cancel_reason VARCHAR(255) COMMENT '取消原因',
    scheduled_delivery_time VARCHAR(20) COMMENT '预约发货时间',
    warehouse_id VARCHAR(50) COMMENT '仓库ID',
    warehouse_name VARCHAR(100) COMMENT '仓库名称',
    is_secure_purchase VARCHAR(1) COMMENT '是否安心购',
    ad_channel VARCHAR(50) COMMENT '广告渠道',
    traffic_type VARCHAR(50) COMMENT '流量类型',
    traffic_content_type VARCHAR(50) COMMENT '流量体裁',
    traffic_channel VARCHAR(50) COMMENT '流量渠道',
    delivery_entity VARCHAR(50) COMMENT '发货主体',
    delivery_entity_detail VARCHAR(100) COMMENT '发货主体明细',
    delivery_time VARCHAR(20) COMMENT '发货时间',
    price_cut_discount VARCHAR(20) COMMENT '降价类优惠',
    platform_discount_actual VARCHAR(20) COMMENT '平台实际承担优惠金额',
    merchant_discount_actual VARCHAR(20) COMMENT '商家实际承担优惠金额',
    talent_discount_actual VARCHAR(20) COMMENT '达人实际承担优惠金额',
    estimated_delivery_time VARCHAR(20) COMMENT '预计送达时间',
    is_platform_warehouse_flow VARCHAR(1) COMMENT '是否平台仓自流转',
    vehicle_type VARCHAR(50) COMMENT '车型',
    product_69_code VARCHAR(50) COMMENT '商品69码',
    delivery_sn VARCHAR(100) COMMENT '发货SN码',
    delivery_imei1 VARCHAR(50) COMMENT '发货IMEI码1',
    delivery_imei2 VARCHAR(50) COMMENT '发货IMEI码2',
    scheduled_delivery_time_end VARCHAR(20) COMMENT '预约送达时间',
    suggest_delivery_start VARCHAR(20) COMMENT '建议发货时间（起）',
    suggest_delivery_end VARCHAR(20) COMMENT '建议发货时间（止）',
    logistics_sn VARCHAR(100) COMMENT '物流SN码',
    logistics_imei1 VARCHAR(50) COMMENT '物流IMEI码1',
    logistics_imei2 VARCHAR(50) COMMENT '物流IMEI码2',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '抖音_后台_订单明细日数据';


-- 抖音_后台_退款明细日数据
drop table if exists sales_dy_ht_refund_details_dly;
CREATE TABLE sales_dy_ht_refund_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    after_sale_id VARCHAR(255) COMMENT '售后单号',
    order_id VARCHAR(255) COMMENT '订单号',
    product_order_id VARCHAR(255) COMMENT '商品单号',
    product_name VARCHAR(255) COMMENT '商品名称',
    product_id VARCHAR(255) COMMENT '商品ID',
    payable_amount VARCHAR(20) COMMENT '应付金额（元）',
    shipping_fee VARCHAR(20) COMMENT '商品运费（元）',
    payment_discount VARCHAR(20) COMMENT '支付优惠（元）',
    tax_amount VARCHAR(20) COMMENT '商品税费（元）',
    delivery_status VARCHAR(20) COMMENT '商品发货状态',
    after_sale_type VARCHAR(20) COMMENT '售后类型',
    refund_amount VARCHAR(20) COMMENT '退商品金额（元）',
    refund_shipping_fee VARCHAR(20) COMMENT '退运费金额（元）',
    refund_payment_discount VARCHAR(20) COMMENT '退支付优惠（元）',
    refund_tax_amount VARCHAR(20) COMMENT '退税费金额（元）',
    after_sale_status VARCHAR(50) COMMENT '售后状态',
    apply_time VARCHAR(255) COMMENT '售后申请时间',
    refund_method VARCHAR(50) COMMENT '退款方式',
    is_refund_proof_uploaded VARCHAR(5) COMMENT '是否已上传退款凭证',
    after_sale_reason VARCHAR(255) COMMENT '售后原因',
    reason_tag VARCHAR(50) COMMENT '售后原因标签',
    return_logistics_no VARCHAR(50) COMMENT '退货物流单号',
    return_abnormal VARCHAR(255) COMMENT '退货异常',
    return_delivery_time VARCHAR(20) COMMENT '退货发货时间',
    logistics_company VARCHAR(50) COMMENT '退货物流公司',
    auto_process_deadline VARCHAR(255) COMMENT '自动处理截止时间',
    approve_time VARCHAR(255) COMMENT '同意售后申请时间',
    merchant_refund_time VARCHAR(255) COMMENT '商家退款时间',
    user_receive_time VARCHAR(255) COMMENT '用户到账时间',
    close_time VARCHAR(255) COMMENT '售后关闭时间',
    return_address VARCHAR(255) COMMENT '商家退货地址',
    contact_name VARCHAR(50) COMMENT '商家退货联系人姓名',
    contact_phone VARCHAR(20) COMMENT '商家退货联系人电话',
    arbitration_status VARCHAR(50) COMMENT '仲裁状态',
    dispute_party VARCHAR(50) COMMENT '纠纷责任方',
    is_express_refund VARCHAR(5) COMMENT '是否极速退款',
    is_refund_after_rejection VARCHAR(5) COMMENT '是否拒签后退款',
    ship_logistics_no VARCHAR(255) COMMENT '发货物流单号',
    ship_logistics_status VARCHAR(50) COMMENT '发货物流状态',
    exchange_logistics_no VARCHAR(255) COMMENT '换货物流单号',
    return_logistics_status VARCHAR(50) COMMENT '退货物流状态',
    finish_time VARCHAR(20) COMMENT '售后完结时间',
    order_remark VARCHAR(500) COMMENT '订单备注',
    user_remark VARCHAR(500) COMMENT '用户售后说明',
    after_sale_remark VARCHAR(500) COMMENT '售后备注',
    operator TEXT COMMENT '操作人',
    negotiation_record TEXT COMMENT '协商记录',
    exchange_product_info TEXT COMMENT '换货商品信息',
    merchant_code VARCHAR(255) COMMENT '商家编码',
    shop_name VARCHAR(100) COMMENT '门店名称',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '抖音_后台_退款明细日数据';


-- 抖音_巨量引擎_全域推广费数据
drop table if exists sales_dy_jlyq_universe_promotion_fee_details_dly;
CREATE TABLE sales_dy_jlyq_universe_promotion_fee_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    catch_path VARCHAR(255) COMMENT '取数路径',
    stat_date VARCHAR(64) COMMENT '日期',
    account_name VARCHAR(64) COMMENT '账户名称',
    account_id VARCHAR(32) COMMENT '账户ID',
    cost VARCHAR(32) COMMENT '消耗',
    total_orders VARCHAR(16) COMMENT '整体成交订单数',
    actual_payment_amount VARCHAR(32) COMMENT '用户实际支付金额',
    total_amount VARCHAR(32) COMMENT '整体成交金额',
    roi VARCHAR(32) COMMENT '整体支付ROI',
    order_cost VARCHAR(32) COMMENT '整体成交订单成本',
    presale_orders VARCHAR(16) COMMENT '整体预售订单数',
    presale_amount VARCHAR(32) COMMENT '整体预售订单金额',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_catch_path(catch_path),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '抖音_巨量引擎_全域推广费数据';

-- 抖音_巨量引擎_标准推广费数据
drop table if exists sales_dy_jlyq_standard_promotion_fee_details_dly;
CREATE TABLE sales_dy_jlyq_standard_promotion_fee_details_dly (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    data_date VARCHAR(255) COMMENT '数据日期',
    data_get_datetime VARCHAR(255) COMMENT '数据流入时间',
    login_account VARCHAR(512) COMMENT '登入账号',
    store_id VARCHAR(64) COMMENT '店铺ID',
    store_name VARCHAR(64) COMMENT '店铺',
    stat_date VARCHAR(64) COMMENT '日期',
    account VARCHAR(64) COMMENT '账户',
    account_id VARCHAR(32) COMMENT '账户id',
    account_tag VARCHAR(128) COMMENT '账户标签',
    status VARCHAR(16) COMMENT '账户状态',
    balance VARCHAR(32) COMMENT '通用余额',
    available_balance VARCHAR(32) COMMENT '通用可用余额',
    bid_grant VARCHAR(32) COMMENT '竞价赠款余额',
    bid_non_grant VARCHAR(32) COMMENT '竞价非赠款余额',
    cost VARCHAR(32) COMMENT '消耗',
    new_followers VARCHAR(16) COMMENT '新增关注数',
    shares VARCHAR(16) COMMENT '分享数',
    comments VARCHAR(16) COMMENT '评论数',
    likes VARCHAR(16) COMMENT '点赞数',
    plays VARCHAR(16) COMMENT '播放数',
    orders VARCHAR(16) COMMENT '成交订单数',
    direct_roi VARCHAR(32) COMMENT '直接支付roi',
    order_amount VARCHAR(32) COMMENT '成交订单金额',
    impressions VARCHAR(32) COMMENT '展示数',
    ctr VARCHAR(16) COMMENT '点击率(%)',
    cpm VARCHAR(32) COMMENT '平均千次展现费用(元)',
    clicks VARCHAR(32) COMMENT '点击数',
    conversions VARCHAR(16) COMMENT '转化数',
    conversion_rate VARCHAR(16) COMMENT '转化率(%)',
    conversion_cost VARCHAR(32) COMMENT '转化成本',
    -- 添加索引
    INDEX idx_data_date (data_date),
    INDEX idx_data_get_datetime (data_get_datetime),
    INDEX idx_login_account (login_account),
    INDEX idx_store_id(store_id),
    INDEX idx_store_name(store_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '抖音_巨量引擎_标准推广费数据';

